modLoader = "javafml"
loaderVersion = "${forge_version_range}"
license = "${licence}"
issueTrackerURL = "${issue_tracker}"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${display_name}"
# updateJSONURL = ""
displayURL = "${website}"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${authors}"
description='''${description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory=true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "{minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.${mod_id)}]
    catalogueImageIcon = "${mod_id}.png"
    configuredBackground = "${mod_id}:textures/item/broccoli.png"
